name: rubiks_cube_solver
description: "Solver de Cubo Mágico"

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  back_button_interceptor: ^7.0.3
  cuber: ^0.4.0
  cupertino_icons: ^1.0.6
  flag: ^7.0.0
  flutter_blue_plus: ^1.32.0
  flutter_colorpicker: ^1.0.3
  flutter_cube: ^0.1.1
  flutter_spinkit: ^5.2.1
  image_picker: ^1.0.7
  intl: ^0.18.1
  path: ^1.8.3
  permission_handler: ^11.3.1
  sensors_plus: ^4.0.2
  sqflite: ^2.3.2
  url_launcher: ^6.2.5

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/images/
    - assets/cube/
